<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                version="1.1">

<xsl:output method="text" />
<xsl:include href="lib.xsl"/>

<xsl:template match="/">    

<xsl:variable name="moduleName"
  select="/Module/@name" />
<xsl:message>Processing CommRMI for module <xsl:value-of select="$moduleName" /></xsl:message>

<xsl:variable name="filename"
  select="concat('src/xtremweb/core/com/com/CommRMI',$moduleName,'.java')" />
<xsl:message>Creating <xsl:value-of select="$filename" /></xsl:message>
<xsl:document href="{$filename}" method="text">
package xtremweb.core.com.com;

/**
 * CommRMI<xsl:value-of select="Module/@name" />.java
 *
 *  Creates RMI Communication to an RMI server
 *
 * This code is generated with from TODO
 * the definition file used TODO
 *
 * Do not edit this file
 *
 * @author fedak
 * @version "1.0"
 */

import xtremweb.core.com.idl.*;
import xtremweb.core.iface.Interface<xsl:value-of select="$moduleName"/>;
import xtremweb.core.obj.<xsl:value-of select="Module/@name" />.*;
import java.rmi.*;
<xsl:value-of select="Module/@import" />

public class CommRMI<xsl:value-of select="$moduleName"/> extends CommRMITemplate implements Interface<xsl:value-of select="$moduleName"/> {

  <xsl:for-each select="/Module/Method">
    <xsl:call-template name="java-method">
      <xsl:with-param name="moduleName" select="$moduleName" />
      <xsl:with-param name="methodName" select="." />
      <xsl:with-param name="params"
        select="./Param" />
      <xsl:with-param name="return"
        select="./Return" />
    </xsl:call-template>
  </xsl:for-each>
}
</xsl:document>
</xsl:template>


<!-- The main template for a Java Method -->
<xsl:template name="java-method">
<xsl:param name="moduleName" />
<xsl:param name="methodName" />
<xsl:param name="params" />
<xsl:param name="return" />

<!-- Builds the attributes --> 
     public <xsl:value-of select="concat($return/@type , ' ', $methodName/@name)"/>( <xsl:call-template name="params-to-list"><xsl:with-param name="params" select="$params"/></xsl:call-template> ) throws RemoteException  {
         <xsl:if test="$return/@type!='void'"><xsl:value-of select="concat($return/@type , ' x;')"/></xsl:if>
         try {
              <xsl:if test="$return/@type!='void'">x = </xsl:if><xsl:value-of select="concat('((Interface', $moduleName, ') rmi ).',$methodName/@name)"/>( <xsl:call-template name="params-to-untyped-list"><xsl:with-param name="params" select="$params"/></xsl:call-template> );
         } catch (RemoteException e) {
		 throw new RemoteException(" " +e);
	}
         return<xsl:if test="$return/@type!='void'"> x</xsl:if>;
     }
</xsl:template>



</xsl:stylesheet>
