<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                version="1.1">

  <xsl:output method="text"/>

<xsl:template match="/">    

<xsl:variable name="moduleName"
  select="Module/@name" />
<xsl:message>Processing Object module <xsl:value-of select="$moduleName" /></xsl:message>

<xsl:for-each select="/Module/Object">
  <xsl:variable name="filename"
    select="concat('src/xtremweb/core/obj/',$moduleName,'/',@name,'.java')" />
  <xsl:message>Creating <xsl:value-of select="$filename" /></xsl:message>
  <xsl:document href="{$filename}" method="text">
    <xsl:call-template name="java-class">
      <xsl:with-param name="className" select="." />
      <xsl:with-param name="attributes"
        select="/Attribute" />
      <xsl:with-param name="moduleName" select="$moduleName" />
    </xsl:call-template>
  </xsl:document>
</xsl:for-each>

</xsl:template>

<!-- The main template for a POXWO --> 

<xsl:template name="java-class">
<xsl:param name="className" />
<xsl:param name="attributes" />
<xsl:param name="moduleName" />

package xtremweb.core.obj.<xsl:value-of select="$moduleName"/>;
import xtremweb.core.uid.UID;
import xtremweb.core.poxwo.Poxwo;
import org.jpox.poid.AUID;
import java.io.*;
import java.util.*;

/**
 * <xsl:value-of select="$className/@name" />.java
 *
 * Declaration of object <xsl:value-of select="$className/@name"/>
 *
 * This code is generated with XwIDL from
 * the definition file used TODO
 *
 * Do not edit this file !
 *
 * @author fedak
 * @version "1.0"
 */

public class <xsl:value-of select="$className/@name" /> extends Poxwo implements Serializable {
<!-- Builds the attributes --> 

<xsl:for-each select="$className/Attribute"> <xsl:if test="@desc">    // <xsl:value-of select="@desc"/>
</xsl:if>
    private <xsl:value-of select="concat(@type, ' ', @name)"/>;

</xsl:for-each>

<xsl:for-each select="$className/Attribute">    public <xsl:value-of select="@type"/> get<xsl:value-of select="@name"/>() {
        return this.<xsl:value-of select="@name" />;
    }
    public void set<xsl:value-of select="@name" /> (<xsl:value-of select="concat(@type,' ', @name)"/>){
        this.<xsl:value-of select="@name" />=<xsl:value-of select="@name" />;
    }

</xsl:for-each>
}
</xsl:template>


</xsl:stylesheet>
