<?xml version="1.0"?>

<Module name="bench" import="import xtremweb.core.obj.dc.Data;">

<Object name="Resultat">
<Attribute  name="uid" type="String" desc="Uniq Identifier"/>
</Object>

<Method name="register">
<Param name="hostName" type="String" desc="hostName of benched machine" />
<Return type="long" desc="workerId"/>
</Method>


<Method name="startExperience">
<Return type="long" desc="null" />
</Method>


<Method name="startExperienceBroadcast">
<Return type="Data" desc="retourn de l'experience" />
</Method>


<Method name="endExperience">
<Param name="workerid" type="long" desc="workerindex"/>
<Param name="measure" type="long" desc="la valeur mesuree"/>
<Param name="vecteur" type="String[]" desc="vecteur de valeurs"/>
<Return type="void" desc="null"/>
</Method>

<Method name="getValues">
<Return type="String[]" desc="liste des valeurs"/>
</Method>

</Module>

