
package xtremweb.core.log;

/**
 * Version of BitDew package.
 *
 * Do not modify this file, it is generated by the build system.
 */
public class Version {
    public final static String version = "1.1.2";

    public static String versionToString() {
        return version;
    }
}
      